package com.dmz.basic.model;

import java.math.BigDecimal;
import java.util.Date;

public class FdsDividendRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.dividend_record_uuid
     *
     * @mbggenerated
     */
    private String dividendRecordUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.ym_id
     *
     * @mbggenerated
     */
    private Long ymId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.member_no
     *
     * @mbggenerated
     */
    private String memberNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.ym_account_id
     *
     * @mbggenerated
     */
    private String ymAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.payment_method_id
     *
     * @mbggenerated
     */
    private String paymentMethodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.dividend_record_date
     *
     * @mbggenerated
     */
    private Date dividendRecordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.dividend_land_date
     *
     * @mbggenerated
     */
    private Date dividendLandDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.fund_code
     *
     * @mbggenerated
     */
    private String fundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.fee_type
     *
     * @mbggenerated
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.dividend_amount
     *
     * @mbggenerated
     */
    private BigDecimal dividendAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.dividend_trans_share
     *
     * @mbggenerated
     */
    private BigDecimal dividendTransShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.ta_confirm_code
     *
     * @mbggenerated
     */
    private String taConfirmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fds_dividend_record.combine_code
     *
     * @mbggenerated
     */
    private String combineCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.id
     *
     * @return the value of t_fds_dividend_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.id
     *
     * @param id the value for t_fds_dividend_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.dividend_record_uuid
     *
     * @return the value of t_fds_dividend_record.dividend_record_uuid
     *
     * @mbggenerated
     */
    public String getDividendRecordUuid() {
        return dividendRecordUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.dividend_record_uuid
     *
     * @param dividendRecordUuid the value for t_fds_dividend_record.dividend_record_uuid
     *
     * @mbggenerated
     */
    public void setDividendRecordUuid(String dividendRecordUuid) {
        this.dividendRecordUuid = dividendRecordUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.ym_id
     *
     * @return the value of t_fds_dividend_record.ym_id
     *
     * @mbggenerated
     */
    public Long getYmId() {
        return ymId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.ym_id
     *
     * @param ymId the value for t_fds_dividend_record.ym_id
     *
     * @mbggenerated
     */
    public void setYmId(Long ymId) {
        this.ymId = ymId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.member_no
     *
     * @return the value of t_fds_dividend_record.member_no
     *
     * @mbggenerated
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.member_no
     *
     * @param memberNo the value for t_fds_dividend_record.member_no
     *
     * @mbggenerated
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.ym_account_id
     *
     * @return the value of t_fds_dividend_record.ym_account_id
     *
     * @mbggenerated
     */
    public String getYmAccountId() {
        return ymAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.ym_account_id
     *
     * @param ymAccountId the value for t_fds_dividend_record.ym_account_id
     *
     * @mbggenerated
     */
    public void setYmAccountId(String ymAccountId) {
        this.ymAccountId = ymAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.payment_method_id
     *
     * @return the value of t_fds_dividend_record.payment_method_id
     *
     * @mbggenerated
     */
    public String getPaymentMethodId() {
        return paymentMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.payment_method_id
     *
     * @param paymentMethodId the value for t_fds_dividend_record.payment_method_id
     *
     * @mbggenerated
     */
    public void setPaymentMethodId(String paymentMethodId) {
        this.paymentMethodId = paymentMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.dividend_record_date
     *
     * @return the value of t_fds_dividend_record.dividend_record_date
     *
     * @mbggenerated
     */
    public Date getDividendRecordDate() {
        return dividendRecordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.dividend_record_date
     *
     * @param dividendRecordDate the value for t_fds_dividend_record.dividend_record_date
     *
     * @mbggenerated
     */
    public void setDividendRecordDate(Date dividendRecordDate) {
        this.dividendRecordDate = dividendRecordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.dividend_land_date
     *
     * @return the value of t_fds_dividend_record.dividend_land_date
     *
     * @mbggenerated
     */
    public Date getDividendLandDate() {
        return dividendLandDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.dividend_land_date
     *
     * @param dividendLandDate the value for t_fds_dividend_record.dividend_land_date
     *
     * @mbggenerated
     */
    public void setDividendLandDate(Date dividendLandDate) {
        this.dividendLandDate = dividendLandDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.fund_code
     *
     * @return the value of t_fds_dividend_record.fund_code
     *
     * @mbggenerated
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.fund_code
     *
     * @param fundCode the value for t_fds_dividend_record.fund_code
     *
     * @mbggenerated
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.fee_type
     *
     * @return the value of t_fds_dividend_record.fee_type
     *
     * @mbggenerated
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.fee_type
     *
     * @param feeType the value for t_fds_dividend_record.fee_type
     *
     * @mbggenerated
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.dividend_amount
     *
     * @return the value of t_fds_dividend_record.dividend_amount
     *
     * @mbggenerated
     */
    public BigDecimal getDividendAmount() {
        return dividendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.dividend_amount
     *
     * @param dividendAmount the value for t_fds_dividend_record.dividend_amount
     *
     * @mbggenerated
     */
    public void setDividendAmount(BigDecimal dividendAmount) {
        this.dividendAmount = dividendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.dividend_trans_share
     *
     * @return the value of t_fds_dividend_record.dividend_trans_share
     *
     * @mbggenerated
     */
    public BigDecimal getDividendTransShare() {
        return dividendTransShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.dividend_trans_share
     *
     * @param dividendTransShare the value for t_fds_dividend_record.dividend_trans_share
     *
     * @mbggenerated
     */
    public void setDividendTransShare(BigDecimal dividendTransShare) {
        this.dividendTransShare = dividendTransShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.ta_confirm_code
     *
     * @return the value of t_fds_dividend_record.ta_confirm_code
     *
     * @mbggenerated
     */
    public String getTaConfirmCode() {
        return taConfirmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.ta_confirm_code
     *
     * @param taConfirmCode the value for t_fds_dividend_record.ta_confirm_code
     *
     * @mbggenerated
     */
    public void setTaConfirmCode(String taConfirmCode) {
        this.taConfirmCode = taConfirmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fds_dividend_record.combine_code
     *
     * @return the value of t_fds_dividend_record.combine_code
     *
     * @mbggenerated
     */
    public String getCombineCode() {
        return combineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fds_dividend_record.combine_code
     *
     * @param combineCode the value for t_fds_dividend_record.combine_code
     *
     * @mbggenerated
     */
    public void setCombineCode(String combineCode) {
        this.combineCode = combineCode;
    }
}