package com.dmz.basic.model;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;

@XmlRootElement
public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.user_no
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.passwd
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.platform
     *
     * @mbggenerated
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.has_passwd
     *
     * @mbggenerated
     */
    private Integer hasPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.pwd_strength
     *
     * @mbggenerated
     */
    private Integer pwdStrength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_login.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.id
     *
     * @return the value of dmz_login.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.id
     *
     * @param id the value for dmz_login.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.user_no
     *
     * @return the value of dmz_login.user_no
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.user_no
     *
     * @param userNo the value for dmz_login.user_no
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.login_name
     *
     * @return the value of dmz_login.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.login_name
     *
     * @param loginName the value for dmz_login.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.passwd
     *
     * @return the value of dmz_login.passwd
     *
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.passwd
     *
     * @param passwd the value for dmz_login.passwd
     *
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.platform
     *
     * @return the value of dmz_login.platform
     *
     * @mbggenerated
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.platform
     *
     * @param platform the value for dmz_login.platform
     *
     * @mbggenerated
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.has_passwd
     *
     * @return the value of dmz_login.has_passwd
     *
     * @mbggenerated
     */
    public Integer getHasPasswd() {
        return hasPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.has_passwd
     *
     * @param hasPasswd the value for dmz_login.has_passwd
     *
     * @mbggenerated
     */
    public void setHasPasswd(Integer hasPasswd) {
        this.hasPasswd = hasPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.pwd_strength
     *
     * @return the value of dmz_login.pwd_strength
     *
     * @mbggenerated
     */
    public Integer getPwdStrength() {
        return pwdStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.pwd_strength
     *
     * @param pwdStrength the value for dmz_login.pwd_strength
     *
     * @mbggenerated
     */
    public void setPwdStrength(Integer pwdStrength) {
        this.pwdStrength = pwdStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.status
     *
     * @return the value of dmz_login.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.status
     *
     * @param status the value for dmz_login.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.is_delete
     *
     * @return the value of dmz_login.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.is_delete
     *
     * @param isDelete the value for dmz_login.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.create_time
     *
     * @return the value of dmz_login.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.create_time
     *
     * @param createTime the value for dmz_login.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_login.update_time
     *
     * @return the value of dmz_login.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_login.update_time
     *
     * @param updateTime the value for dmz_login.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}