package com.dmz.basic.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.user_no
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.hobbys
     *
     * @mbggenerated
     */
    private String hobbys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.is_single
     *
     * @mbggenerated
     */
    private Integer isSingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.is_straight
     *
     * @mbggenerated
     */
    private Integer isStraight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.photo_no
     *
     * @mbggenerated
     */
    private String photoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.video_no
     *
     * @mbggenerated
     */
    private String videoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmz_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.id
     *
     * @return the value of dmz_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.id
     *
     * @param id the value for dmz_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.user_no
     *
     * @return the value of dmz_user.user_no
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.user_no
     *
     * @param userNo the value for dmz_user.user_no
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.gender
     *
     * @return the value of dmz_user.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.gender
     *
     * @param gender the value for dmz_user.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.avatar
     *
     * @return the value of dmz_user.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.avatar
     *
     * @param avatar the value for dmz_user.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.hobbys
     *
     * @return the value of dmz_user.hobbys
     *
     * @mbggenerated
     */
    public String getHobbys() {
        return hobbys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.hobbys
     *
     * @param hobbys the value for dmz_user.hobbys
     *
     * @mbggenerated
     */
    public void setHobbys(String hobbys) {
        this.hobbys = hobbys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.is_single
     *
     * @return the value of dmz_user.is_single
     *
     * @mbggenerated
     */
    public Integer getIsSingle() {
        return isSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.is_single
     *
     * @param isSingle the value for dmz_user.is_single
     *
     * @mbggenerated
     */
    public void setIsSingle(Integer isSingle) {
        this.isSingle = isSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.is_straight
     *
     * @return the value of dmz_user.is_straight
     *
     * @mbggenerated
     */
    public Integer getIsStraight() {
        return isStraight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.is_straight
     *
     * @param isStraight the value for dmz_user.is_straight
     *
     * @mbggenerated
     */
    public void setIsStraight(Integer isStraight) {
        this.isStraight = isStraight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.photo_no
     *
     * @return the value of dmz_user.photo_no
     *
     * @mbggenerated
     */
    public String getPhotoNo() {
        return photoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.photo_no
     *
     * @param photoNo the value for dmz_user.photo_no
     *
     * @mbggenerated
     */
    public void setPhotoNo(String photoNo) {
        this.photoNo = photoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.video_no
     *
     * @return the value of dmz_user.video_no
     *
     * @mbggenerated
     */
    public String getVideoNo() {
        return videoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.video_no
     *
     * @param videoNo the value for dmz_user.video_no
     *
     * @mbggenerated
     */
    public void setVideoNo(String videoNo) {
        this.videoNo = videoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.is_delete
     *
     * @return the value of dmz_user.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.is_delete
     *
     * @param isDelete the value for dmz_user.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.create_time
     *
     * @return the value of dmz_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.create_time
     *
     * @param createTime the value for dmz_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmz_user.update_time
     *
     * @return the value of dmz_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmz_user.update_time
     *
     * @param updateTime the value for dmz_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}