package com.dmz.basic.mapper;

import com.dmz.basic.model.AwardHistoryImportDetail;
import java.util.List;

public interface AwardHistoryImportDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_award_history_import_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_award_history_import_detail
     *
     * @mbggenerated
     */
    int insert(AwardHistoryImportDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_award_history_import_detail
     *
     * @mbggenerated
     */
    AwardHistoryImportDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_award_history_import_detail
     *
     * @mbggenerated
     */
    List<AwardHistoryImportDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_award_history_import_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AwardHistoryImportDetail record);
}