package com.dmz.basic.model;

import java.util.Date;

public class AwardHistoryImportDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.import_his_id
     *
     * @mbggenerated
     */
    private Long importHisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.stat_start_time
     *
     * @mbggenerated
     */
    private Date statStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.stat_end_time
     *
     * @mbggenerated
     */
    private Date statEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.fail_path
     *
     * @mbggenerated
     */
    private String failPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_award_history_import_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.id
     *
     * @return the value of t_award_history_import_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.id
     *
     * @param id the value for t_award_history_import_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.import_his_id
     *
     * @return the value of t_award_history_import_detail.import_his_id
     *
     * @mbggenerated
     */
    public Long getImportHisId() {
        return importHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.import_his_id
     *
     * @param importHisId the value for t_award_history_import_detail.import_his_id
     *
     * @mbggenerated
     */
    public void setImportHisId(Long importHisId) {
        this.importHisId = importHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.stat_start_time
     *
     * @return the value of t_award_history_import_detail.stat_start_time
     *
     * @mbggenerated
     */
    public Date getStatStartTime() {
        return statStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.stat_start_time
     *
     * @param statStartTime the value for t_award_history_import_detail.stat_start_time
     *
     * @mbggenerated
     */
    public void setStatStartTime(Date statStartTime) {
        this.statStartTime = statStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.stat_end_time
     *
     * @return the value of t_award_history_import_detail.stat_end_time
     *
     * @mbggenerated
     */
    public Date getStatEndTime() {
        return statEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.stat_end_time
     *
     * @param statEndTime the value for t_award_history_import_detail.stat_end_time
     *
     * @mbggenerated
     */
    public void setStatEndTime(Date statEndTime) {
        this.statEndTime = statEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.status
     *
     * @return the value of t_award_history_import_detail.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.status
     *
     * @param status the value for t_award_history_import_detail.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.fail_path
     *
     * @return the value of t_award_history_import_detail.fail_path
     *
     * @mbggenerated
     */
    public String getFailPath() {
        return failPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.fail_path
     *
     * @param failPath the value for t_award_history_import_detail.fail_path
     *
     * @mbggenerated
     */
    public void setFailPath(String failPath) {
        this.failPath = failPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.create_time
     *
     * @return the value of t_award_history_import_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.create_time
     *
     * @param createTime the value for t_award_history_import_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_award_history_import_detail.update_time
     *
     * @return the value of t_award_history_import_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_award_history_import_detail.update_time
     *
     * @param updateTime the value for t_award_history_import_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}