package com.dmz.basic.mapper;

import com.dmz.basic.model.FdsDividendRecord;
import java.util.List;

public interface FdsDividendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fds_dividend_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fds_dividend_record
     *
     * @mbggenerated
     */
    int insert(FdsDividendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fds_dividend_record
     *
     * @mbggenerated
     */
    FdsDividendRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fds_dividend_record
     *
     * @mbggenerated
     */
    List<FdsDividendRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fds_dividend_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FdsDividendRecord record);
}