package com.dmz.basic.mapper;

import com.dmz.basic.model.Login;
import java.util.List;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dmz_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey__(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dmz_login
     *
     * @mbggenerated
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dmz_login
     *
     * @mbggenerated
     */
    List<Login> selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dmz_login
     *
     * @mbggenerated
     */
    List<Login> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dmz_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Login record);

    List<Login> selectLoginByLogin(Login login);
}